apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nfs-pod-access-control-certificate
  namespace: nfs-pod-ac
spec:
  secretName: nfs-pod-access-control-tls
  dnsNames:
    - nfs-pod-access-control-webhook.nfs-pod-ac.svc
  issuerRef:
    name: self-signer
    kind: ClusterIssuer
    group: cert-manager.io
