apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nfs-pod-access-control-certificate
  namespace: default
spec:
  secretName: nfs-pod-access-control-tls
  dnsNames:
    - nfs-pod-access-control-webhook.default.svc
  issuerRef:
    name: self-signer
