apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-pod-access-control
  namespace: nfs

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nfs
  name: configmap-reader
rules:
- apiGroups: ["*"]
  resources: ["configmaps"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-binding
  namespace: nfs
subjects:
- kind: ServiceAccount
  name: nfs-pod-access-control
  namespace: nfs
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io

