---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nfs-pod-access-control
  name: nfs-pod-access-control
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 30100
  selector:
    app: nfs-pod-access-control
