#!/bin/bash

## Create namespace for the webhook
kubectl create namespace nfs

## Create certificate for the webhook
kubectl apply -f dev/manifests/cert-manager/nfs-pod-access-control-certificate.yaml

## Install helm package
helm install nfs-pod-access-control helm -n nfs --create-namespace

## Map NFS users in configmap
scripts/add-user user1 1001
scripts/add-user user2 1002
scripts/add-user user3 1003



