apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-webhook
  name: {{ .Release.Name }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Release.Name }}-webhook

