apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "nfs-pod-access-control.k8s.com"
  annotations:
    cert-manager.io/inject-ca-from: default/nfs-pod-access-control-certificate
webhooks:
  - name: "nfs-pod-access-control.k8s.com"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: nfs-pod-access-control
        path: /validate-pods
        port: 443
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
